### ISSUE TITLE
Write a React component for previewing links

### ISSUE THREAD

**Issue by paulrberg** [hifi-finance/docs#1]
See https://github.com/facebookincubator/infima/issues/194.

**Comment by PaulRBerg** [comment]
This turned out to be much more complicated than I had anticipated.

One can't retrieve the metadata of an URL without a proxy server. Using [OpenGraph](https://opengraph.io) is an alternative, but the free plan offers only 100 requests per month.

Focusing on this at this point in time is not worth it.

**Comment by PaulRBerg** [comment]
**Update**: I ended up writing the component, but it's not a dynamic one. It requires the icon, the title and the subtitle to be passed manually, but that's good enough for now.

https://github.com/hifi-finance/docs/commit/282b29df33adbc3a8a324bdc2aaca590ed9ac2fb
